### ISSUE TITLE
Hello, I want to ask what is wrong with this error?

### ISSUE THREAD

**Issue by luffymu** [Unity-Technologies/facial-ar-remote#10]
![cuowu](https://user-images.githubusercontent.com/43170958/45354443-37ef2c80-b5f0-11e8-962a-a6c45c9bf258.jpg)

**Comment by mtschoen-unity** [comment]
It looks like a problem in your blendshapes controller. It appears this will happen if the number of overrides exceeds the number of blendshapes in the stream definition.

Are you trying to use a different head model than the example? Does the example scene still work? Can you give a little more information about your setup?

**Comment by luffymu** [comment]
Thank you very much for your reply, this problem has been solved, but I don't know why, when I use the pc computer, it will always be stuck when I run, I have to restart unity!

**Comment by mtschoen-unity** [comment]
Hm. So now that you have fixed this issue, you get a hang when you try to run play mode? That is quite odd. Unfortunately, it will be hard to diagnose the issue without seeing your project. Are you willing to submit your project files via the bug reporter?

You can do so by going to Help > Report a bug

**Comment by kamihiro** [comment]
Hi, I had the same issue with this error. I couldn't fix it, so I submit the project for the bug reporter.
hope hear something from you.
Thank you.

**Comment by mtschoen-unity** [comment]
I'm glad to know you were able to fix the error. I believe that e0c6ab6 fixes this issue, in that it removes the default value of 51.

**Comment by jcMed4** [comment]
Hello, I've been setting up the example project and I have been getting this error as well. Updating the scripts as suggested hasn't helped. I should note that I'm using Stream Settings ARKit 2.0, but I don't get the error on Stream Settings ARKit 1.5, however, 1.5 makes the facial capture update **_very_** slowly. I was wondering if anyone could offer some insight? Thanks!
