### ISSUE TITLE
Can this record blendshape animation and audio at the same time?

### ISSUE THREAD

**Issue by AVOlight** [Unity-Technologies/facial-ar-remote#13]
Hi, also wondering when there will be more content on this workflow?
i've only found [one blog post](https://blogs.unity3d.com/2018/08/13/facial-ar-remote-animating-with-ar/) and the [short demo in the keynote](https://www.youtube.com/watch?v=cn94iMQqnpU)

**Comment by mtschoen-unity** [comment]
Hi there, thanks for your interest in the project. Unfortunately, we do not plan to produce any more content with this project. We're always interested to know what people are making with Unity, so feel free to share your own content with us on social media!

As for your audio question, there are no plans to add audio recording to this project. We have found that it works well enough to use the device's screen recording, or record the actor with a second camera with audio, and then just manually sync the tracks to account for any network lag. If you wanted to build audio recording directly into the pipeline, I believe that it would work to initiate a local audio recording on the device when the session is joined. You could then later extract the clips that you need along with timestamps in the recorded blendshapes. Alternatively, you could initiate recording in response to some network message when you press record in the editor. The latter solution would be tricky as there is currently no data stream going from the editor to the phone.

**Comment by AVOlight** [comment]
Hello, Thank you for the info :)
