### ISSUE TITLE
Is this awesomeness still a live project with you guys at Labs ?

### ISSUE THREAD

**Issue by jonKaio** [Unity-Technologies/facial-ar-remote#15]
Also regardless, is there a list of the various blend shapes or a document detailing the workflow we can put in front of our artists for them to follow so we end up with our own character art that works with it?

(Just saw this at Unite and was wowed by it)

**Comment by SometimesSean** [comment]
You can find the blendshape docs on Apple's developer site https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation
