### ISSUE TITLE
QuaternionToEuler: Input quaternion was not normalized - on baking animation clip

### ISSUE THREAD

**Issue by kkarannn** [Unity-Technologies/facial-ar-remote#17]
//Error occurs when baking animation clip:
QuaternionToEuler: Input quaternion was not normalized
UnityEditor.AnimationUtility:SetEditorCurve(AnimationClip, EditorCurveBinding, AnimationCurve)
Unity.Labs.FacialRemote.ClipBaker:ApplyAnimationCurves() (at Assets/facial-ar-remote-master/Remote/Scripts/Editor/ClipBaker.cs:171)
Unity.Labs.FacialRemote.StreamReaderEditor:BakeClipLoop() (at Assets/facial-ar-remote-master/Remote/Scripts/Editor/StreamReaderEditor.cs:299)
Unity.Labs.FacialRemote.StreamReaderEditor:OnInspectorGUI() (at Assets/facial-ar-remote-master/Remote/Scripts/Editor/StreamReaderEditor.cs:253)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

//Followed by this error:
Assertion failed on expression: 'IsFinite(rot)'
UnityEditor.AnimationUtility:SetEditorCurve(AnimationClip, EditorCurveBinding, AnimationCurve)
Unity.Labs.FacialRemote.ClipBaker:ApplyAnimationCurves() (at Assets/facial-ar-remote-master/Remote/Scripts/Editor/ClipBaker.cs:171)
Unity.Labs.FacialRemote.StreamReaderEditor:BakeClipLoop() (at Assets/facial-ar-remote-master/Remote/Scripts/Editor/StreamReaderEditor.cs:299)
Unity.Labs.FacialRemote.StreamReaderEditor:OnInspectorGUI() (at Assets/facial-ar-remote-master/Remote/Scripts/Editor/StreamReaderEditor.cs:253)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by jonathan-unity** [comment]
I found an issue with recording and baking for ARKit 2.0 where we were not setting the frame time offset value in the playback buffer. A fix has been pushed to `Master` and `Develop` that will work for new recordings.
If you need to fix an old recording you can hand set the value in your `PlaybackData` in a text editor. For any playback buffers with a `m_BlendShapeCount:` of `52` set `m_FrameTimeOffset:` to `269`
I hope that fixes the Issue.

**Comment by hawajk** [comment]
Is there someone fix this, I got the same error!
