### ISSUE TITLE
Baking Animation Records only first Keyframe

### ISSUE THREAD

**Issue by polae** [Unity-Technologies/facial-ar-remote#18]
I'm able to use the remote with the sloth character, record animation and playback using the player on the stream recorder component.   When I bake the animation, however, the Animation Clip produced contains only one keyframe at the head of each blendshape / animation track.  

Considering that the Playback Buffer contains the animation which can be played back on the character, it step that's failing us is the bake.   Might someone have some insight on how to remedy this?  Perhaps something not in the documentation that we're missing?  

Thank you in advance for any help you can offer on this front!

**Comment by kkarannn** [comment]
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor.Experimental.Animations;

public class FaceRecorder : MonoBehaviour
{
    

    Animator FaceController;

    public AnimationClip CurrentRecordingClip;

    public bool m_Recording = false;
    GameObjectRecorder m_FaceRecorder;

    // Use this for initialization
    void Start () {
        m_FaceRecorder = new GameObjectRecorder(this.gameObject);
        m_FaceRecorder.BindComponentsOfType<SkinnedMeshRenderer>(gameObject, false);

        FaceController = GetComponent<Animator>();
		
	}
	
	// Update is called once per frame
	void Update () {
        if(Input.GetKeyDown(KeyCode.Space))
        {
            m_Recording = !m_Recording;
        }
		
	}
    private void LateUpdate()
    {
        if(CurrentRecordingClip == null)
        {
            return;
        }
        if(m_Recording)
        {
            m_FaceRecorder.TakeSnapshot(Time.deltaTime);
        }
        else if(m_FaceRecorder.isRecording)
        {
            m_FaceRecorder.SaveToClip(CurrentRecordingClip);
            m_FaceRecorder.ResetRecording();
        }
    }

    
}`

**Comment by jonathan-unity** [comment]
I think this might be this issue https://github.com/Unity-Technologies/facial-ar-remote/issues/17

**Comment by mtschoen-unity** [comment]
Hey there @polae. Have you tried using the latest version to see if this resolves your issue? Please let us know if this is still a problem, and re-open the issue. Otherwise, thanks for reporting! :)

**Comment by samusmclame** [comment]
> //Use the following script on the gameobject with skinned mesh renderer component, along with blend shape driver script.
> //Give it an empty animation clip to record animation.
> //Hit Space key to record animation in play mode and hit space again to stop recording.
> //Enjoy
> 
> using System.Collections;
> using System.Collections.Generic;
> using UnityEngine;
> using UnityEditor.Experimental.Animations;
> 
> public class FaceRecorder : MonoBehaviour
> {
> 
> ```
> public AnimationClip CurrentRecordingClip;
> public bool m_Recording = false;
> GameObjectRecorder m_FaceRecorder;
> 
> // Use this for initialization
> void Start () {
>     m_FaceRecorder = new GameObjectRecorder(this.gameObject);
>     m_FaceRecorder.BindComponentsOfType<SkinnedMeshRenderer>(gameObject, false);
> 
>     
> 	
> }
> 
> // Update is called once per frame
> void Update () {
>     if(Input.GetKeyDown(KeyCode.Space))
>     {
>         m_Recording = !m_Recording;
>     }
> 	
> }
> private void LateUpdate()
> {
>     if(CurrentRecordingClip == null)
>     {
>         return;
>     }
>     if(m_Recording)
>     {
>         m_FaceRecorder.TakeSnapshot(Time.deltaTime);
>     }
>     else if(m_FaceRecorder.isRecording)
>     {
>         m_FaceRecorder.SaveToClip(CurrentRecordingClip);
>         m_FaceRecorder.ResetRecording();
>     }
> }
> ```
> 
> }

I know I'm grave digging but it's super important for me, is there a way you specifically add it? i  often do this kind of thing wrong in unity, are we supposed to create an entire other script and apply it?
