### ISSUE TITLE
Suggestions for ideal head and neck bone rig?

### ISSUE THREAD

**Issue by somlor** [Unity-Technologies/facial-ar-remote#20]
Thanks for this project! Our company is using Unity Pro and a fork of this for an iOS app we're shipping January 2019.

We do have some questions about the head and neck bone setup if you could help us out.

![unity 2018 3 0f2 - madden unity - gigan - iphone ipod touch and ipad metal 2018-12-19 17-04-57](https://user-images.githubusercontent.com/81008/50250943-464ba200-03b0-11e9-8b37-63f0d0809fdd.png)

1. Should one bone/joint be a parent of the other? e.g. turning neck bone turns head or vice versa?
2. What is ideal location for these bones? e.g. neck bone in center of neck mass at shoulder height, head bone in center of head mass at eye level? 
3. Roughly what are suggested vertex assignments? e.g. all of neck up to jawline assigned to neck bone, entire rest of head assigned to head bone?

Thanks again, any pointers at all would be very _very_ appreciated! 🙌

**Comment by jonathan-unity** [comment]
1. In my setups I have the neck being the child of the my last spine joint going up the spine and the head as a child to the neck. So the Spines rotation drives the neck and the neck drive the head.
2. I used sort of the standard game rig layout for my joints in DCC tool, where the neck joint is about shoulder height and the head is at the base of the skull where the skull joins the spine.
3. Again my weighting is pretty standard, the neck bone's influence starts a little bit before the height of the bone with full influence just above or around the height of the neck bone. This influence goes up the neck and the head completely takes over by the time you hit the jaw bone (physical jaw bone not talking about the digital join) and the base of the head on the back. In my DCC I usually pose my character and have them going through some poses to check the skin weighting. 
The setup of the character head and neck follow is just simple lerpping of the head anchor from ARKit.  It is only an approximation more like puppeteering the character's head than any sort of simulation. The head anchor is not really meant to be an accurate location of the base of the head. It kind of looks like the pivot of the blend shape meshes in ARKit are closer to the center of the face mask and the anchor is a node offset from that. It seems like this sense, I notice drift in the head anchor pose when changing my expression but keeping the rest of my head a still as possible.
