### ISSUE TITLE
Eye driver only works if character looks towards -Z

### ISSUE THREAD

**Issue by simonbroggi** [Unity-Technologies/facial-ar-remote#22]
When using the Drive Eyes setting in Character Rig Controller, the pitch of the eye transforms is inverted if the character looks towards positive Z (as in the Sloth Example).

To reproduce
- Open the scene Examples/Scenes/SlothBlendShapes
- Add shapes for left and right eyes and add them as Left Eye / Right Eye in Character Rig Controller
- Set Drive Eyes tu True, and eye look distance to something positiv (should pe positive if the character looks towards positive Z, right??)

**Comment by jonathan-unity** [comment]
Some of the rotation is a bit weird and I should add some debug options to show the look targets and look vectors for the character. Even thought it is a positive offset the locator my be behind the eye bone. These directions and offsets are all going to be in a local space not world.
I will look into the setup you are describing more and see if I can figure out the issue you are running into.

**Comment by simonbroggi** [comment]
it's very weird! Could it be different on osX and Windows? I fixed the problem for me by rotating the character 180 around Y axis, but when changing operating system the eyes look up when they should look down and vice versa again..
