### ISSUE TITLE
Invalid AR Blendshapes?

### ISSUE THREAD

**Issue by jcMed4** [Unity-Technologies/facial-ar-remote#23]
I have imported a model with blendshapes and some of them work perfectly, but a great number of them(mostly mouth and eye movements) don't work and I have a lot of this error:

**Blend shape BS_node.eyeBlinkLeft is not a valid AR blend shape**
**UnityEngine.Debug:LogWarningFormat(String, Object[])
Unity.Labs.FacialRemote.BlendShapesController:UpdateBlendShapeIndices(IStreamSettings) (at Assets/facial-ar-remote/Remote/Scripts/BlendShapesController.cs:178)
Unity.Labs.FacialRemote.BlendShapesController:Update() (at Assets/facial-ar-remote/Remote/Scripts/BlendShapesController.cs:121)**

<img width="511" alt="screen shot 2019-02-14 at 1 08 02 pm" src="https://user-images.githubusercontent.com/47635719/52807404-5bb01600-3059-11e9-917c-288800e30145.png">

Does anyone know why this might be happening?

**Comment by jonathan-unity** [comment]
The plugin uses a the naming that matches the internal string name for the blend shape in the ARKit plugin. If you look at `BlendShapeUtils` you can see the name that the facial remote is expecting for a given shape.
There is a way to use custom naming for a blend shape. Within the Stream Settings you are using on your Network Stream component on the StreaReader game object, you are able to create mappings from one name to another with the Mappings of the stream Settings.
![2019-02-15_13h22_40](https://user-images.githubusercontent.com/22459473/52885068-dbef7d80-3124-11e9-8e40-e76ff2e74461.png)

**Comment by jcMed4** [comment]
Thank you! This worked perfectly!
