### ISSUE TITLE
BlendShapesController streamReader coming up Null

### ISSUE THREAD

**Issue by jcMed4** [Unity-Technologies/facial-ar-remote#24]
Hi, in the BlendShapesController and CharacterRigController scripts, the IStreamReader streamReader is returning Null for one of my new meshes. I have put in two custom meshes before this one and they never had this problem. I'm not sure what to look into or change on the new one to have it fill the streamReader like the others. Does anyone else know why something wouldn't be able to find it?

**Comment by mtschoen-unity** [comment]
I'm guessing you solved your own issue? What was the fix?

**Comment by jcMed4** [comment]
I did fix it, but I'm honestly not sure. I reopened Unity, re-ran the game a few times, re-setup the mesh, etc.

One of the tries, it worked for no apparent reason and I didn't have the problem again.

**Comment by mtschoen-unity** [comment]
Huh. Sounds like maybe a serialization/validation bug in our inspector? If you can find a reliable way to reproduce the issue please let us know and we can try to come up with a fix. Glad to hear you're unblocked, though!

**Comment by jcMed4** [comment]
Okay! If I find a way to reproduce it, I'll let you know!
