### ISSUE TITLE
Hi, thanks for documents, I also specially to save bought a new ipadpro11 inch, but process is stuck in the middle, the run on FaceARRemote displayed when "Device Not Supported. Both Please use iPhone X." that is Not compatible with the new ipadpro?Hope can get help, thank you

### ISSUE THREAD

**Issue by 18street** [Unity-Technologies/facial-ar-remote#25]

**Comment by jonathan-unity** [comment]
The iPad pro 3rd gen of devices is compatible with face tracking but my require you to update some things on our mac. The compatibility check is coming internally from XCode and iOS when you build the project.  Check and see if you are running an up to date version of XCode (10.x+). You can check if there are updates for Xcode on the Mac App Store. You may also need to set the iOS minimum deployment target to 12 in your XCode build settings for the app.

**Comment by gn00410660** [comment]
We are actually using an iPhone XR for testing, and it is showing that the device is not compatible, is an iPhone X strictly required for using the script? We did, however try it with an iPhone X, and it worked.
