### ISSUE TITLE
Eye driver using bones runs backwards on some models.

### ISSUE THREAD

**Issue by Janooba** [Unity-Technologies/facial-ar-remote#26]
The eyes on some models (I tested with Mixamo/Fuse models) end up looking back into the skull.

This can obviously be fixed by editing the offset from -0.5 to 0.5, but then the up and down is reversed.

After some digging I found where this is updated, and added a bool to reverse the pitch.

I recommend adding a bool to flip the pitch to the driver options.
(example)
```csharp
// ~line 412 of CharacterRigController.cs - duplicated for right eye just below
var leftEyePitch = Quaternion.AngleAxis((m_EyeLookUpLeft - m_EyeLookDownLeft) * m_EyeAngleRange.x, m_FlipEyePitch ? Vector3.left : Vector3.right);
```

**Comment by Janooba** [comment]
After playing with yet another character model with completely different structure/layout, they used y-up as forward direction for their eyes. It may be worth either allowing the user to set a specific direction as "forward" for the eyes, or use the default position as forward.

**Comment by bradweiers** [comment]
Good catch @Janooba. We'll look into this for the next release.

**Comment by fengkan** [comment]
Is there any update on this issue?

**Comment by bradweiers** [comment]
Please see the latest update and let me know if it's still an issue.
