### ISSUE TITLE
use facial-ar-remote1.1 and ARKit2.0, but tongueOut useless

### ISSUE THREAD

**Issue by hawajk** [Unity-Technologies/facial-ar-remote#29]
use facial-ar-remote1.1 and ARKit2.0( server and client), but tongueOut useless, I check the name of tongue blend shape, and also drag this to the component "blend shape controller" ,and change the count to 52. 
Everything looks working well but when i stick out my tongue, it looks like not been tracking.Is there any step i missing?

**Comment by mtschoen-unity** [comment]
Hi there.

What are you doing with the blendshapes? Are you using the provided sloth example? If so, this is the reason you aren't seeing anything happen on the tongueOut blendshape. The model was created before ARKit 2.0 was released, and doesn't have a tongue! :)

If you are actually trying to drive something with the tongueOut blendshape, and it is missing, let us know. All 52 blendshapes should be getting data.

**Comment by hawajk** [comment]
![1](https://user-images.githubusercontent.com/25243348/58307214-9aabef80-7e30-11e9-8260-1e5b5231d312.jpg)
![2](https://user-images.githubusercontent.com/25243348/58307216-9bdd1c80-7e30-11e9-8198-0851d0e0a92b.jpg)

It is the model i  create, and  the pictures shows the tongue blendshape, Is there any mistake?

**Comment by bradweiers** [comment]
@hawajk did you figure it out? Might have been that you needed to use the updated StreamSettings asset.
