### ISSUE TITLE
Missing steps in docs

### ISSUE THREAD

**Issue by SometimesSean** [Unity-Technologies/facial-ar-remote#3]
Hey, just spotted a couple of steps that are missed on the build settings docs.

1. import TMP Essential Resources for TextMesh Pro
2. Enable "ARKit Uses Facetracking" on UnityARKitPlugin > Resources > UnityARKitPlugIn > ARKitSettings

I wasn't familiar with either, so I spent a bit of time working this out. Hopefully it will save some others the headache. Otherwise, great work guys, I'm going to get a lot of use out of this.

**Comment by jonathan-unity** [comment]
Thanks for the feedback. I will update and clarify that in the docs.

**Comment by jalemanyf** [comment]
Hi,

I'm trying to test the amazing Facial AR Remote sample.

I'm following all the documentation steps ( maybe I done something wrong or missing ).

The App works on my iPhone X: I see the mask over my face and all the gestures. GREAT!

On the Unity Editor I open the scene SlothBlendShapes.

My IP is 192.168.1.31 PORT: 9000

I put on muy iPhone App and press connect but... nothing never happends :(

I only receive two warnings ( not errors ) on the Unity Console: 

Missing mesh in Sloth_Head2 (UnityEngine.SkinnedMeshRenderer)
UnityEngine.Debug:LogWarning(Object)
Unity.Labs.FacialRemote.BlendShapesController:Start() (at Assets/Remote/Scripts/BlendShapesController.cs:72)

Any Ideas?

Thanks!

**Comment by mtschoen-unity** [comment]
@jalemanyf I've closed this issue by addressing the two missing steps in the original report. If you continue to have issues, please open a new issue so we can track yours.
