### ISSUE TITLE
2.0 branch readme links to private/unavailable repo

### ISSUE THREAD

**Issue by Janooba** [Unity-Technologies/facial-ar-remote#31]
In the 2.0-update branch, the [readme.md](https://github.com/Unity-Technologies/facial-ar-remote/blob/2.0-update/readme.md) suggests that the [ar-face-capture-remote](https://github.com/Unity-Technologies/com.unity.xr.ar-face-capture-remote) repo needs to be used to build the iPhone app, but this repo is private or unavailable. Is this still under construction, or just an oversight?

**Comment by bradweiers** [comment]
It's still under construction. Stay tuned.
