### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Jazz-mang** [Unity-Technologies/facial-ar-remote#36]
After I load the unitypackage into Unity2018 1.1f1, the Console showed 
"Assets/facial-ar-remote/Remote/Scripts/ClientGUI.cs(5,7): error CS0246: The type or namespace name `TMPro' could not be found. Are you missing an assembly reference?" 
& 
"Assets/facial-ar-remote/Remote/Scripts/ClientGUI.cs(49,9): error CS0246: The type or namespace name `TMP_InputField' could not be found. Are you missing an assembly reference?"
Could you help to fix it? I appreciate that. :)

**Comment by bradweiers** [comment]
From the readme:

> (Unity 2018.1) Add TextMesh-Pro to the project from Window > Package Manager. The package is added automatically in Unity 2018.2 and above.

**Comment by Jazz-mang** [comment]
The problem is fixed, thank you so much! :)
