### ISSUE TITLE
Questions about releasing applications using facial-ar-remote.

### ISSUE THREAD

**Issue by Jazz-mang** [Unity-Technologies/facial-ar-remote#37]
Dear Unity, I've encountered a problem: the thing is, if I want to put facial-ar-remote into my unity projects, what do I need to do? Is it necessary to get a Developer Account and is there a must to publish the application through mac book? If not, could you please recommend some detailed introductions and tutorials about it, API instruction is also great for me.
Thanks. Looking forward to receive your reply.

**Comment by Jazz-mang** [comment]
by the way, you said the Git LFS contained the whole assets about the facial-ar-remote project, so could you please tell me where can get the path? Thanks!

**Comment by AFeiYA** [comment]
- - 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bradweiers** [comment]
Please see [Getting started with iOS development](https://docs.unity3d.com/Manual/iphone-GettingStarted.html).

Also [Git Basics - Getting a Git Repository](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository).
