### ISSUE TITLE
Exception Errors 

### ISSUE THREAD

**Issue by dgon-jd** [Unity-Technologies/facial-ar-remote#4]
Hi!

I'm getting errors after establishing connection. 
One time:
`NullReferenceException: Object reference not set to an instance of an object
Unity.Labs.FacialRemote.BlendShapesController.UpdateBlendShapeIndices (IStreamSettings settings) (at Assets/facial-ar-remote-master/Remote/Scripts/BlendShapesController.cs:106)
Unity.Labs.FacialRemote.BlendShapesController.Update () (at Assets/facial-ar-remote-master/Remote/Scripts/BlendShapesController.cs:76)
`

and a lot of:

`KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary 2[UnityEngine.SkinnedMeshRenderer,Unity.Labs.FacialRemote.BlendShapeIndexData[]].get_Item (UnityEngine.SkinnedMeshRenderer key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
Unity.Labs.FacialRemote.BlendShapesController.Update () (at Assets/facial-ar-remote-master/Remote/Scripts/BlendShapesController.cs:82)
`

What it could be?

**Comment by mtschoen** [comment]
It looks like you are targeting a skinned mesh renderer that is missing its mesh reference. Are you using the example scene with the sloth character or your own mesh?

**Comment by mtschoen-unity** [comment]
I added a check for this in a1d474d
