### ISSUE TITLE
Use different blendshape names

### ISSUE THREAD

**Issue by jaraen** [Unity-Technologies/facial-ar-remote#40]
Hi,

I've been able to build the iOS client and run the Sloth demo. I'm trying now to do the same with some custom character, but blendshape names are different (although they do the same morphs required by ARKit). What's the best way to map these names from the StreamReader to my SkinnedMeshRenderer?

I see some `mapping.cs` script and a `BlendShapeUtils.cs` file that contains a list of arkit blendshapes, but I'm not sure if modifying these files is the right way to do it.

Thanks

Note: modifying the original 3D file is not an option, since it's a bought character from a library

**Comment by jonathan-unity** [comment]
Hi Jaraen,
Take a look at Mappings in the stream settings. I think this issue is similar to the one you are having https://github.com/Unity-Technologies/facial-ar-remote/issues/23
Let me know you need more help or this is not working as expected.

**Comment by jaraen** [comment]
cool, thanks!
