### ISSUE TITLE
Project doesn't work

### ISSUE THREAD

**Issue by SoundGuy** [Unity-Technologies/facial-ar-remote#41]
Is this project still being maintained?

I'm attempting to  get it to work with iPhone 11 pro, and Unity 2019.2, 
I have to remove the limitation for IphoneX in the client code, and disable my windows firewall and finally managed to get it to connect, but then the stream data doesn't affect the sloth.

**Comment by tobeglad** [comment]
@SoundGuy here is a plugin I wrote recently. It supports Unity 2019.2 or newer and has Face Tracking remote for Editor. It is paid, meaning I'm committed to support it and add new features in the future.
https://forum.unity.com/threads/ar-foundation-editor-remote-test-and-debug-your-ar-project-in-the-editor.898433/#post-5933453

**Comment by bradweiers** [comment]
Please see the latest update.
