### ISSUE TITLE
Unable To Connect

### ISSUE THREAD

**Issue by GaryQuah** [Unity-Technologies/facial-ar-remote#46]
Hi , I downloaded and launched the package, but am unable to connect my IOS to the editor.
I have tried disabling my windows firewall. I am running the app on an I-Pad pro.

Steps tried to execute the project : 
1) Run editor
2) Check IP and Port number printed in console is same on the IOS device
3) Press connect.
I have tried printing out the error message in the Client, and it read exception : Connection timed out. Ive tried searching information about the facial-ar-remote and cant find much information, none the less for the error.

Thankful for any insights to my connecting issue, cheers.

**Comment by bradweiers** [comment]
Are you sure that the machine running the editor and the iOS device are on the same network? Also make sure that the network on the Windows side (if on a PC) is set to "Private" not "Public".

**Comment by GaryQuah** [comment]
Thanks ! It works now after setting my Ethernet to private. Does this work with any blendshapes model? while searching for a blendshapes model what should I look out for to make this work the best?

**Comment by GaryQuah** [comment]
Thanks, after applying your suggestion I can connect
