### ISSUE TITLE
Compiled App on App store

### ISSUE THREAD

**Issue by TheCarelessWhisper** [Unity-Technologies/facial-ar-remote#49]
has anyone just compiled this and put it on the app store? I've compiled this a few times, only for it to just stop working for some reason. now I don't have my MacBook to push it to the iPhone. is there anyone who just put it up on the app store?

**Comment by SoundGuy** [comment]
I'm not sure what's the license, but i'm currently attempting to build it, if it's ok i might consider uploading it but i don't know if apple will approve it.

**Comment by mtschoen-unity** [comment]
Hi there! We have now published the [Unity Face Capture](https://apps.apple.com/nz/app/unity-face-capture/id1544159771) app to the iOS App Store, which serves the same function as this app. Unity Face Capture provides all the same functionality as this project, which is now discontinued. Thanks for your interest in face capture and good luck on your project!
