### ISSUE TITLE
Can this build windows program?

### ISSUE THREAD

**Issue by spartancc** [Unity-Technologies/facial-ar-remote#5]
UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x0021f] in /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:187 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x0007f] in /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:94 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Examples/Scenes/SlothBlendShapes.scene
Build windows program in mac system

![wx20180822-123859](https://user-images.githubusercontent.com/42367711/44443319-c122cd00-a609-11e8-992a-4a827592a7bd.png)

**Comment by mtschoen-unity** [comment]
Hmm, I don't see why you couldn't build a Windows player version of the server/streamreader, but we've designed this as an editor tool with an attached iOS app. We should definitely fix these build errors, though. Thanks for the report. I'll post an update with a fix soon.

If you wanted to be able to connect to a phone in a player app, all you would theoretically need to do is create a GUI for the StreamReader. Bear in mind that features like baking animation clips will not be available in players.

**Comment by jonathan-unity** [comment]
I have pushed a new `develope` branch that has the fix for this. This will be added to `master` soon.

**Comment by spartancc** [comment]
thanks

**Comment by spartancc** [comment]
Can I package the windows program now?
![wx20180917-185201](https://user-images.githubusercontent.com/42367711/45619154-d37a1480-baaa-11e8-95a7-377514cc7fa1.png)

**Comment by jonathan-unity** [comment]
@spartancc you should be able to if you switch over to the `develop` branch. We have not pushed these changes to `master` or the release package yet.

**Comment by jonathan-unity** [comment]
@spartancc It looks the the stream reader you have selected is in the project view and the character is in a scene. Make sure you select the stream reader in the scene and assign a character in the scene as well.

**Comment by spartancc** [comment]
Thank you, can this project recognize the tongue?

**Comment by spartancc** [comment]
![win err](https://user-images.githubusercontent.com/42367711/49024888-72bb3680-f1d5-11e8-9399-38c57f8bf21f.png)
Can't package window

**Comment by spartancc** [comment]
> ![win err](https://user-images.githubusercontent.com/42367711/49024888-72bb3680-f1d5-11e8-9399-38c57f8bf21f.png)
> Can't package window


Sorry, develop can package windows
