### ISSUE TITLE
ARBlendshapeLocation dose not contain a define for "TongueOut"

### ISSUE THREAD

**Issue by brq1992** [Unity-Technologies/facial-ar-remote#7]
I used the Unity2018.2.5 Personal(64bit), switched the platform to iOS, but the console still warned this error

**Comment by brq1992** [comment]
btw, I got the new version of arkit plugin from the Bitbucket

**Comment by robinnorth** [comment]
You need to check out the `tip` tag from the ARKit plugin Mercurial repository -- the `default` branch doesn't include the ARKit 2.0 changes.

**Comment by mtschoen-unity** [comment]
@robinnorth is/was correct. The default branch is currently at the tip. Latest versions of everything should avoid this issue.
