### ISSUE TITLE
ImportFBX errors

### ISSUE THREAD

**Issue by Henrilux** [Unity-Technologies/facial-ar-remote#9]
Hi there

I just had import fbx errors at unity master end. Seems like a broken fbx model. would you be able to help? Error screenshot attached below. thanks heaps and look forward to your reply.

![unity screenshot import fbx errors](https://user-images.githubusercontent.com/43144582/45306995-851bc180-b550-11e8-870d-782220b7fa13.png)

**Comment by jonathan-unity** [comment]
If you are using GitHub's download zip it does not include large files in the zip. Otherwise be sure you have lfs (large file system) running in your git repo. https://git-lfs.github.com/

**Comment by mtschoen-unity** [comment]
I've added a unity package to avoid confusion with LFS and the github zip download. You should be able to download the unitypackage linked here, import it, get TextMeshPro (if you don't already have it in your project) and be up and running.

https://github.com/Unity-Technologies/facial-ar-remote/releases

**Comment by Henrilux** [comment]
awesome problem solved!
